import { test, expect } from '@playwright/test'
test('generic draw playground edits and round-trips GeoJSON with atomic import validation', async ({ page }) => {
  await page.goto('/#draw'); await expect(page.locator('#status')).toContainText('左键添加点')
  await page.getByRole('button', { name: '生成示例几何', exact: true }).click()
  await page.getByRole('button', { name: '拖动顶点', exact: true }).click()
  await page.getByRole('button', { name: '导出 GeoJSON', exact: true }).click()
  await expect(page.locator('#status')).toContainText('请先完成或取消')
  await page.getByRole('button', { name: '确认编辑', exact: true }).click()
  await page.getByRole('button', { name: '导出 GeoJSON', exact: true }).click()
  const data = JSON.parse(await page.locator('#draw-geojson').inputValue())
  expect(data.features).toHaveLength(1); expect(data.features[0].geometry.type).toBe('Polygon')
  await page.locator('#draw-geojson').fill('{"type":"Polygon","coordinates":[]}')
  await page.getByRole('button', { name: '导入 GeoJSON', exact: true }).click()
  await expect(page.locator('#status')).toContainText('操作失败'); await expect(page.locator('#resources')).toContainText('Entity 1')
  await page.locator('#draw-geojson').fill(JSON.stringify(data)); await page.getByRole('button', { name: '导入 GeoJSON', exact: true }).click()
  await expect(page.locator('#status')).toContainText('已导入 1 个几何对象')
  await page.locator('#cleanup').click(); await expect(page.locator('#resources')).toContainText('容器残留 0')
})
async function ready(page) {
  await page.goto('/draw-validation.html')
  await page.waitForFunction(() => window.drawValidation?.viewer.scene.frameState.frameNumber > 2)
  await page.evaluate(() => window.drawValidation.start())
  await page.waitForTimeout(300)
}
async function drag(page, point, dx, dy) {
  await page.mouse.move(point.x, point.y); await page.mouse.down()
  await expect.poll(() => page.evaluate(() => window.drawValidation.state().inputs)).toBe(false)
  await page.mouse.move(point.x + dx, point.y + dy, { steps: 6 }); await page.mouse.up()
  await expect.poll(() => page.evaluate(() => window.drawValidation.state().inputs)).toBe(true)
}
test('vertex drag is one undo step, retains height and commits metadata on the original Entity', async ({ page }, testInfo) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message)); await ready(page)
  const before = await page.evaluate(() => window.drawValidation.state())
  const point = await page.evaluate(() => window.drawValidation.handle(0))
  await drag(page, point, -35, 15)
  const after = await page.evaluate(() => window.drawValidation.state())
  expect(after.draft[0].longitude).not.toBe(before.draft[0].longitude)
  expect(after.draft[0].height).toBeCloseTo(100, 5); expect(after.committed).toEqual(before.committed)
  const history = await page.evaluate(() => { const { editor } = window.drawValidation; const first = editor.undo(), second = editor.undo(), redo = editor.redo(); return { first, second, redo } })
  expect(history).toEqual({ first: true, second: false, redo: true })
  // Native geometry rebuilds asynchronously; verify the polygon is rendered before capturing it.
  await expect.poll(() => page.evaluate(() => {
    const app = window.drawValidation
    return app.viewer.scene.drillPick(app.center()).some(entry => entry.id === app.result.entity)
  })).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('polygon-edit.png') })
  const committed = await page.evaluate(() => { const app = window.drawValidation, entity = app.result.entity; const result = app.editor.finish(); return { same: result === app.result && result.entity === entity, feature: app.kit.toGeoJSON(result), state: app.state(), errors: app.errors } })
  expect(committed.same).toBe(true); expect(committed.feature.id).toBe('polygon')
  expect(committed.feature.properties).toEqual({ name: '示例多边形', rules: { enabled: true } })
  expect(committed.state.entities).toBe(1); expect(committed.errors).toEqual([]); expect(errors).toEqual([])
})
test('midpoint insertion, vertex deletion, whole movement and cancellation restore geometry and camera', async ({ page }) => {
  await ready(page)
  await page.evaluate(() => window.drawValidation.editor.setMode('insert'))
  await page.waitForTimeout(100)
  const midpoint = await page.evaluate(() => window.drawValidation.handle(4))
  await page.mouse.click(midpoint.x, midpoint.y)
  await expect.poll(() => page.evaluate(() => window.drawValidation.editor.positions.length)).toBe(5)
  await page.evaluate(() => window.drawValidation.editor.setMode('delete'))
  await page.waitForTimeout(100)
  const vertex = await page.evaluate(() => window.drawValidation.handle(1))
  await page.mouse.click(vertex.x, vertex.y)
  await expect.poll(() => page.evaluate(() => window.drawValidation.editor.positions.length)).toBe(4)
  await page.evaluate(() => window.drawValidation.editor.setMode('translate'))
  await page.evaluate(() => window.drawValidation.overlay())
  await page.waitForTimeout(200)
  const before = await page.evaluate(() => window.drawValidation.state())
  await drag(page, await page.evaluate(() => window.drawValidation.center()), 30, 12)
  const after = await page.evaluate(() => window.drawValidation.state())
  expect(after.draft[0].longitude).not.toBe(before.draft[0].longitude)
  await page.evaluate(() => window.drawValidation.editor.cancel())
  await page.evaluate(() => window.drawValidation.clearOverlay())
  const cancelled = await page.evaluate(() => window.drawValidation.state())
  expect(cancelled.inputs).toBe(true); expect(cancelled.entities).toBe(1)
  expect(cancelled.committed).toEqual(before.committed)
  expect(await page.evaluate(() => window.drawValidation.errors)).toEqual([])
})
test('cancelling or removing a drawing during a drag releases camera lock and helper entities', async ({ page }) => {
  await ready(page)
  const vertex = await page.evaluate(() => window.drawValidation.handle(0))
  await page.mouse.move(vertex.x, vertex.y); await page.mouse.down()
  await expect.poll(() => page.evaluate(() => window.drawValidation.state().inputs)).toBe(false)
  await page.evaluate(() => window.drawValidation.editor.cancel()); await page.mouse.up()
  expect(await page.evaluate(() => window.drawValidation.state().inputs)).toBe(true)
  await page.evaluate(() => window.drawValidation.start()); await page.waitForTimeout(100)
  const again = await page.evaluate(() => window.drawValidation.handle(0))
  await page.mouse.move(again.x, again.y); await page.mouse.down()
  await page.evaluate(() => { const app = window.drawValidation; app.viewer.entities.remove(app.result.entity); app.kit.getResult(app.result.id) })
  await page.mouse.up()
  expect(await page.evaluate(() => window.drawValidation.state().inputs)).toBe(true)
  expect(await page.evaluate(() => window.drawValidation.viewer.entities.values.length)).toBe(0)
})
